// Generated by `frappe-types gen-registry`. Do not edit; re-run the generator.
//   --app edge_app
//   DocType JSON read from: edge_app
//   customisations read from: (none)
//
// Each interface lists one DocType's data fields as its JSON files declare them, plus
// the Custom Fields and Property Setters of the apps above. `DocOf<DocType>` adds the
// standard fields. Fields added in the database (Customize Form) are in no file and
// so are not here: a registered document is closed, so add any your code reads by
// augmenting `FrappeDocTypeFields`. Other generated files (other apps') can share the
// program: see the frappe-types README, "Generating the registry".

import type * as $ft from "frappe-types";

declare global {
	/**
	 * DocType name -> its data fields. Every entry is an interface of the global
	 * `FrappeDocTypeFields` namespace, so a second generated file that registers the same
	 * DocType declares the same entry, and its fields merge into the same interface.
	 */
	interface FrappeDocTypes {
		"Bank Statement Import Log": FrappeDocTypeFields.BankStatementImportLog;
		"Custom DocPerm": FrappeDocTypeFields.CustomDocPerm;
		"Customize Form": FrappeDocTypeFields.CustomizeForm;
		"Desktop Icon": FrappeDocTypeFields.DesktopIcon;
		"DocType": FrappeDocTypeFields.DocType;
		"Issue": FrappeDocTypeFields.Issue;
		"Web Page": FrappeDocTypeFields.WebPage;
		"e-Invoice Log": FrappeDocTypeFields.eInvoiceLog;
		"e-Waybill Log": FrappeDocTypeFields.eWaybillLog;
		"e-Waybill Log Item": FrappeDocTypeFields.eWaybillLogItem;
	}

	/** The data fields of each registered DocType, by frappe's controller class name. */
	namespace FrappeDocTypeFields {
		/**
		 * DocType "Bank Statement Import Log" — edge_app, module Edge Cases.
		 * `edge_app/edge_app/edge_cases/doctype/bank_statement_import_log/bank_statement_import_log.json`
		 */
		interface BankStatementImportLog {
			/** Bank Account · Link → Bank Account */
			bank_account?: string | null;
			/** Number of Transactions · Int */
			number_of_transactions?: number | null;
			/** Detected Amount Format · Select */
			detected_amount_format?: "Separate columns for withdrawal and deposit" | "Amount column has \"CR\"/\"DR\" values" | "Amount column has positive/negative values" | "Transaction type column has \"CR\"/\"DR\" values" | "Transaction type column has \"Deposit\"/\"Withdrawal\" values" | "Transaction type column has \"C\"/\"D\" values" | "" | null;
			/** PDF Tables · JSON */
			pdf_tables?: unknown;
			/** Status · Select */
			status?: "Not Started" | "Completed" | "" | null;
		}

		/**
		 * DocType "Custom DocPerm" — edge_app, module Edge Cases.
		 * `edge_app/edge_app/edge_cases/doctype/custom_docperm/custom_docperm.json`
		 */
		interface CustomDocPerm {
			/** Role · Link → Role */
			role?: string | null;
			/** If user is the owner · Check */
			if_owner?: 0 | 1;
			/** Level · Int */
			permlevel?: number | null;
			/** Read · Check */
			read?: 0 | 1;
			/** Select · Check */
			select?: 0 | 1;
			/** Delete · Check */
			delete?: 0 | 1;
			/** Import · Check */
			import?: 0 | 1;
			// parent (Data) — a standard field, typed by frappe-types
		}

		/**
		 * DocType "Customize Form" — edge_app, module Edge Cases.
		 * `edge_app/edge_app/edge_cases/doctype/customize_form/customize_form.json`
		 */
		interface CustomizeForm {
			/** Naming Rule · Select */
			naming_rule?: "Set by user" | "By fieldname" | "By \"Naming Series\" field" | "Expression" | "Expression (old style)" | "Random" | "By script" | "" | null;
			/** Enter Form Type · Link → DocType */
			doc_type?: string | null;
			/** Auto Name · Data */
			autoname?: string | null;
		}

		/**
		 * DocType "Desktop Icon" — edge_app, module Edge Cases.
		 * `edge_app/edge_app/edge_cases/doctype/desktop_icon/desktop_icon.json`
		 */
		interface DesktopIcon {
			/** Label · Data */
			label?: string | null;
			// idx (Int) — a standard field, typed by frappe-types
			/** Icon Type · Select */
			icon_type?: "Link" | "Folder" | "App" | "" | null;
			/** Hidden · Check */
			hidden?: 0 | 1;
		}

		/**
		 * DocType "DocType" — edge_app, module Edge Cases.
		 * `edge_app/edge_app/edge_cases/doctype/doctype/doctype.json`
		 */
		interface DocType {
			/** Module · Link → Module Def */
			module?: string | null;
			/** Is Child Table · Check */
			istable?: 0 | 1;
			/** Naming Rule · Select */
			naming_rule?: "Set by user" | "Autoincrement" | "By fieldname" | "By \"Naming Series\" field" | "Expression" | "Expression (old style)" | "Random" | "UUID" | "By script" | "" | null;
			/** Auto Name · Data */
			autoname?: string | null;
		}

		/**
		 * DocType "Issue" — edge_app, module Edge Cases.
		 * `edge_app/edge_app/edge_cases/doctype/issue/issue.json`
		 */
		interface Issue {
			/** Subject · Data */
			subject?: string | null;
			/** Status · Select */
			status?: "Open" | "Replied" | "On Hold" | "Resolved" | "Closed" | "" | null;
			/** Average Response Time · Duration */
			avg_response_time?: number | null;
			/** Resolution Time · Duration */
			resolution_time?: number | null;
			/** First Response Time · Duration */
			first_response_time?: number | null;
		}

		/**
		 * DocType "Web Page" — edge_app, module Edge Cases.
		 * `edge_app/edge_app/edge_cases/doctype/web_page/web_page.json`
		 */
		interface WebPage {
			/** Title · Data */
			title?: string | null;
			/** Route · Data */
			route?: string | null;
			/** Published · Check */
			published?: 0 | 1;
			// idx (Int) — a standard field, typed by frappe-types
			/** Content Type · Select */
			content_type?: "Rich Text" | "Markdown" | "HTML" | "Page Builder" | "Slideshow" | "" | null;
		}

		/**
		 * DocType "e-Invoice Log" — edge_app, module Edge Cases.
		 * `edge_app/edge_app/edge_cases/doctype/e_invoice_log/e_invoice_log.json`
		 */
		interface eInvoiceLog {
			/** IRN · Data */
			irn?: string | null;
			/** e-Waybill Number · Link → e-Waybill Log */
			e_waybill_number?: string | null;
			/** Is Cancelled · Check */
			is_cancelled?: 0 | 1;
		}

		/**
		 * DocType "e-Waybill Log" — edge_app, module Edge Cases.
		 * `edge_app/edge_app/edge_cases/doctype/e_waybill_log/e_waybill_log.json`
		 */
		interface eWaybillLog {
			/** e-Waybill Number · Data */
			e_waybill_number?: string | null;
			/** Is Cancelled · Check */
			is_cancelled?: 0 | 1;
			/** Items · Table → e-Waybill Log Item */
			items: FrappeChildRow<"e-Waybill Log Item">[];
		}

		/**
		 * DocType "e-Waybill Log Item" — edge_app, module Edge Cases.
		 * `edge_app/edge_app/edge_cases/doctype/e_waybill_log_item/e_waybill_log_item.json`
		 */
		interface eWaybillLogItem {
			/** The DocTypes on this bench with a Table of e-Waybill Log Item: the forms its events run on. */
			parenttype: "e-Waybill Log";
			/** Item Code · Data */
			item_code?: string | null;
		}
	}
}

export type BankStatementImportLog = FrappeDocTypeFields.BankStatementImportLog;
export type CustomDocPerm = FrappeDocTypeFields.CustomDocPerm;
export type CustomizeForm = FrappeDocTypeFields.CustomizeForm;
export type DesktopIcon = FrappeDocTypeFields.DesktopIcon;
export type DocType = FrappeDocTypeFields.DocType;
export type Issue = FrappeDocTypeFields.Issue;
export type WebPage = FrappeDocTypeFields.WebPage;
export type eInvoiceLog = FrappeDocTypeFields.eInvoiceLog;
export type eWaybillLog = FrappeDocTypeFields.eWaybillLog;
export type eWaybillLogItem = FrappeDocTypeFields.eWaybillLogItem;
