// Generated by `frappe-types gen-doctypes`. Do not edit; re-run the generator.
//   --app my_app
//
// Each interface is one DocType as its JSON files declare it, plus the Custom Fields
// and Property Setters the apps above ship. Fields added in the database (Customize
// Form) are not in any file; they fall through to FrappeDoc's index signature as
// `unknown`. See the frappe-types README, "Typing your DocTypes".

import type * as $ft from "frappe-types";

declare global {
	/** DocType name -> document shape. Augmented by every generated doctypes file. */
	interface FrappeDocTypes {
		"Delivery Run": DeliveryRun;
		"Delivery Stop": DeliveryStop;
		"Payment Terminal": PaymentTerminal;
		"Sales Order": SalesOrder;
		"Sales Order Item": SalesOrderItem;
		"Sales Order Tag": SalesOrderTag;
		"Selling Settings": SellingSettings;
	}
}

/**
 * DocType "Delivery Run" — my_app, module My App.
 * `my_app/my_app/my_app/doctype/delivery_run/delivery_run.json`
 * `autoname: autoincrement`: the server sends `name` as a number (frappe/model/naming.py:161-162), though `FrappeDoc` types it string.
 */
export interface DeliveryRun extends $ft.FrappeDoc {
	doctype: "Delivery Run";
	/** Route Code · Data */
	"route-code"?: string | null;
	/** Sales Order · Link → Sales Order */
	sales_order?: string | null;
	/** Stops · Table → Delivery Stop */
	stops: DeliveryStop[];
	/** Lines · Table → Sales Order Item */
	lines: SalesOrderItem[];
	/** Duration · Duration */
	duration?: number | null;
	/** Started At · Datetime */
	started_at?: string | null;
	/** Widget · Fancy Widget */
	widget?: unknown;
}

/**
 * DocType "Delivery Stop" — my_app, module My App.
 * `my_app/my_app/my_app/doctype/delivery_stop/delivery_stop.json`
 */
export interface DeliveryStop extends $ft.ChildDoc {
	doctype: "Delivery Stop";
	/** Address · Small Text */
	address?: string | null;
	/** Signature · Signature */
	signature?: string | null;
	/** Parcels · Table → Parcel Line */
	parcels: $ft.ChildDoc[];
}

/**
 * DocType "Payment Terminal".
 * Included because it is customised by my_app/my_app/fixtures/custom_field.json; its DocType JSON is not on this bench, so only its custom fields are typed.
 */
export interface PaymentTerminal extends $ft.FrappeDoc {
	doctype: "Payment Terminal";
	/** Terminal · Data · Custom Field, my_app/my_app/fixtures/custom_field.json */
	custom_terminal_id?: string | null;
}

/**
 * DocType "Sales Order" — base_app, module Selling.
 * `base_app/base_app/selling/doctype/sales_order/sales_order.json`
 * Included because it is customised by my_app/my_app/my_app/custom/sales_order.json.
 */
export interface SalesOrder extends $ft.FrappeDoc {
	doctype: "Sales Order";
	/** Series · Select */
	naming_series?: string | null;
	/** Customer · Link → Customer */
	customer?: string;
	/** Status · Select */
	status?: "Draft" | "On Hold" | "Completed" | "" | null;
	/** Date · Date */
	transaction_date?: string | null;
	/** Is Return · Check */
	is_return?: 0 | 1;
	/** Total Quantity · Int */
	total_qty?: number;
	/** Grand Total · Currency */
	grand_total?: number;
	/** Rating · Rating */
	rating?: number | null;
	/** External Ref · Data */
	external_ref?: string;
	/** Items · Table → Sales Order Item */
	items: SalesOrderItem[];
	/** Tags · Table MultiSelect → Sales Order Tag */
	tags: SalesOrderTag[];
	/** Notes *\/ with a comment terminator · Text Editor */
	notes?: string | null;
	/** Payload · JSON */
	payload?: unknown;
	// idx (Int) — typed by $ft.FrappeDoc
	/** Delivery Run · Link → Delivery Run · Custom Field, my_app/my_app/my_app/custom/sales_order.json */
	custom_delivery_run?: string | null;
	/** Priority · Select · Custom Field, my_app/my_app/my_app/custom/sales_order.json */
	custom_priority?: "Low" | "High" | "" | null;
}

/**
 * DocType "Sales Order Item" — base_app, module Selling.
 * `base_app/base_app/selling/doctype/sales_order_item/sales_order_item.json`
 * Included because it is a child table of Delivery Run.lines.
 */
export interface SalesOrderItem extends $ft.ChildDoc {
	doctype: "Sales Order Item";
	/** Item · Link → Item */
	item_code?: string | null;
	/** Quantity · Float */
	qty?: number;
	/** UOM · Select */
	uom?: "Nos" | "Kg" | "" | null;
}

/**
 * DocType "Sales Order Tag" — base_app, module Selling.
 * `base_app/base_app/selling/doctype/sales_order_tag/sales_order_tag.json`
 * Included because it is a child table of Sales Order.tags.
 */
export interface SalesOrderTag extends $ft.ChildDoc {
	doctype: "Sales Order Tag";
	/** Tag · Link → Tag */
	tag?: string | null;
}

/**
 * DocType "Selling Settings" — base_app, module Selling.
 * `base_app/base_app/selling/doctype/selling_settings/selling_settings.json`
 * Included because it is customised by my_app/my_app/fixtures/custom_field.json.
 * Single: its one document is named after the DocType.
 */
export interface SellingSettings extends $ft.FrappeDoc {
	doctype: "Selling Settings";
	name: "Selling Settings";
	/** Sales Order Required · Select */
	so_required?: "No" | "Yes" | "" | null;
	/** Allow Negative Rates · Check */
	allow_negative_rates?: 0 | 1;
	/** Default Run · Link → Delivery Run · Custom Field, my_app/my_app/fixtures/custom_field.json */
	custom_default_run?: string | null;
}
